version: "3.9"

services:
  app:
    build: .
    container_name: data_project
    command: bash -c "cd AI_API && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"